name: SimpleBanHammer
version: 0.0.1.1
main: com.github.k4runio.simpleBanHammer.SimpleBanHammer
api-version: 1.21
commands:
  banhammer:
    description: Gives you the Ban Hammer item
    permission: simplebanhammer.use
permissions:
  simplebanhammer.reload:
    description: Allows use of the /banhammer reload command
    default: op
  simplebanhammer.use:
    description: Allows use of the /banhammer hammer command
    default: true
